export const newsInterestOptions = [
  { value: "mancing", label: "Mancing" },
  { value: "game", label: "Main Game" },
  { value: "berita", label: "Berita" },
  { value: "olahraga", label: "Olahraga" },
  { value: "hiburan", label: "Hiburan" },
  { value: "teknologi", label: "Teknologi" },
  { value: "sosial", label: "Sosial" },
  { value: "ekonomi", label: "Ekonomi" },
  { value: "budaya", label: "Budaya" },
  { value: "seni", label: "Seni" },
  { value: "musik", label: "Musik" },
  { value: "film", label: "Film" },
  { value: "sastra", label: "Sastra" },
  { value: "travel", label: "Travel" },
  { value: "kuliner", label: "Kuliner" },
  { value: "fashion", label: "Fashion" },
  { value: "kesehatan", label: "Kesehatan" },
  { value: "pendidikan", label: "Pendidikan" },
  { value: "karir", label: "Karir" },
  { value: "kesehatan", label: "Kesehatan" },
  { value: "lingkungan", label: "Lingkungan" },
  { value: "politik", label: "Politik" },
  { value: "hukum", label: "Hukum" },
  { value: "agama", label: "Agama" },
  { value: "spiritualitas", label: "Spiritualitas" },
  { value: "spiritualitas", label: "Spiritualitas" },
] as const;
